export { default as Signup } from './signup/Signup';
export { default as Login } from './login/Login';
export { default as Forgot } from './forgot/Forgot';
export { default as Reset } from './reset/Reset';
export { default as Profile } from './profile/Profile';
export { default as Dashboard } from './dashboard/Dashboard';
export { default as NavMenu } from './navMenu/NavMenu';
export { default as Billing } from './billing/Billing';
export{ default as Footer}  from './footer/Footer';
export { default as Alert } from './alert/Alert';